/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    'service-types': ServiceType;
    portfolio: Portfolio;
    posts: Post;
    categories: Category;
    media: Media;
    comments: Comment;
    leads: Lead;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    'service-types': ServiceTypesSelect<false> | ServiceTypesSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('uk' | 'en') | ('uk' | 'en')[];
  globals: {
    'calculator-config': CalculatorConfig;
  };
  globalsSelect: {
    'calculator-config': CalculatorConfigSelect<false> | CalculatorConfigSelect<true>;
  };
  locale: 'uk' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Наприклад: "Розробка Landing Page"
   */
  title: string;
  /**
   * URL-friendly назва, наприклад: "landing-page"
   */
  slug: string;
  /**
   * Короткий опис для картки на сторінці /services
   */
  shortDescription: string;
  /**
   * Іконка для картки послуги
   */
  icon?: (number | null) | Media;
  /**
   * Головне зображення для сторінки послуги
   */
  heroImage?: (number | null) | Media;
  /**
   * Тип послуги для фільтрації та групування
   */
  serviceType: number | ServiceType;
  /**
   * Порядок відображення (менше число = вище)
   */
  order?: number | null;
  /**
   * Показувати на головній сторінці
   */
  featured?: boolean | null;
  /**
   * Чи доступний варіант на конструкторі Weblium
   */
  hasWebliumOption?: boolean | null;
  /**
   * Вартість варіанту на Weblium
   */
  webliumPrice?: number | null;
  webliumPriceCurrency?: ('UAH' | 'USD' | 'EUR') | null;
  /**
   * Наприклад: "5-7 днів"
   */
  webliumTimeline?: string | null;
  webliumFeatures?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Короткий опис переваг Weblium варіанту
   */
  webliumDescription?: string | null;
  /**
   * Вартість кастомної розробки
   */
  customPrice: number;
  customPriceCurrency: 'UAH' | 'USD' | 'EUR';
  /**
   * Наприклад: "2-3 тижні"
   */
  customTimeline: string;
  customFeatures: {
    feature?: string | null;
    id?: string | null;
  }[];
  /**
   * Короткий опис переваг кастомної розробки
   */
  customDescription: string;
  /**
   * Що таке, для кого, які завдання вирішує
   */
  detailedDescription: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Детальний список що входить в послугу
   */
  whatIncluded?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  process?:
    | {
        /**
         * Наприклад: "01", "02"
         */
        stepNumber?: string | null;
        /**
         * Наприклад: "Аналіз і планування"
         */
        stepTitle?: string | null;
        stepDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Порівняння Weblium vs Custom
   */
  comparisonTable?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Проекти з портфоліо для цієї послуги
   */
  relatedPortfolioProjects?: (number | Portfolio)[] | null;
  /**
   * Інші послуги які можуть зацікавити клієнта
   */
  relatedServices?: (number | Service)[] | null;
  faq?:
    | {
        question?: string | null;
        answer?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Технології які використовуються в послузі
   */
  technologies?:
    | {
        tech?: string | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title?: string | null;
        description?: string | null;
        /**
         * Назва іконки або emoji
         */
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string;
    /**
     * Зображення для соціальних мереж
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Лічильник переглядів сторінки послуги
   */
  viewCount?: number | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Дата публікації послуги
   */
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Опис зображення для SEO та доступності
   */
  alt: string;
  /**
   * Підпис до зображення
   */
  caption?: string | null;
  /**
   * Організація файлів по папках
   */
  folder?: ('posts' | 'categories' | 'portfolio' | 'general') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types".
 */
export interface ServiceType {
  id: number;
  /**
   * Наприклад: "Веб-розробка", "Маркетинг", "Дизайн"
   */
  name: string;
  /**
   * URL-friendly назва, наприклад: "web-development"
   */
  slug: string;
  /**
   * Опис для сторінки /services/[type]
   */
  description: string;
  /**
   * Іконка для відображення в фільтрі
   */
  icon?: (number | null) | Media;
  /**
   * Зображення для OG та заголовка сторінки
   */
  cover?: (number | null) | Media;
  /**
   * Акцентний колір для категорії, наприклад: #3B82F6
   */
  color?: string | null;
  /**
   * Порядок відображення в фільтрі (менше число = вище)
   */
  order?: number | null;
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  /**
   * Опис для картки проекту
   */
  shortDescription: string;
  client: string;
  service: 'design' | 'website' | 'promotion';
  /**
   * Заповнюється тільки якщо service = "Сайт"
   */
  type?: ('custom' | 'builder') | null;
  /**
   * URL проекту (якщо є)
   */
  projectUrl?: string | null;
  /**
   * Дата публікації проекту
   */
  projectDate: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * URL-friendly назва для посилань
   */
  slug: string;
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string;
    /**
     * Зображення для соціальних мереж
     */
    ogImage?: (number | null) | Media;
  };
  viewCount?: number | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Показувати на головній сторінці
   */
  featured?: boolean | null;
  /**
   * Порядок відображення на сайті (менше число = вище)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-friendly назва для посилань
   */
  slug: string;
  /**
   * Опис для превью статті
   */
  description: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | User;
  category: number | Category;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  date: string;
  cover: number | Media;
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string;
  };
  /**
   * Приблизний час читання статті в секундах
   */
  readTime: number;
  status: 'draft' | 'published' | 'archived';
  /**
   * Показувати на головній сторінці
   */
  featured?: boolean | null;
  viewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Визначає рівень доступу користувача
   */
  role: 'superadmin' | 'admin' | 'moderator';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL-friendly назва для посилань
   */
  slug: string;
  description: string;
  /**
   * Наприклад: #3B82F6
   */
  color?: string | null;
  cover?: (number | null) | Media;
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  author: number | User;
  /**
   * До якої статті відноситься коментар
   */
  post: number | Post;
  content: string;
  /**
   * Модерація коментарів адміністратором
   */
  status: 'pending' | 'approved' | 'spam';
  /**
   * Для вкладених відповідей (необов'язково)
   */
  parent?: (number | null) | Comment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  contact: string;
  message?: string | null;
  type: 'simple' | 'calculator';
  calculatorData?: {
    projectType?: string | null;
    platform?: ('weblium' | 'custom') | null;
    pagesCount?: number | null;
    additionalServices?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    urgency?: string | null;
    estimatedPrice?: number | null;
    estimatedTimeline?: string | null;
  };
  source?: string | null;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
  };
  status: 'new' | 'processing' | 'completed' | 'rejected';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'service-types';
        value: number | ServiceType;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  icon?: T;
  heroImage?: T;
  serviceType?: T;
  order?: T;
  featured?: T;
  hasWebliumOption?: T;
  webliumPrice?: T;
  webliumPriceCurrency?: T;
  webliumTimeline?: T;
  webliumFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  webliumDescription?: T;
  customPrice?: T;
  customPriceCurrency?: T;
  customTimeline?: T;
  customFeatures?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  customDescription?: T;
  detailedDescription?: T;
  whatIncluded?: T;
  process?:
    | T
    | {
        stepNumber?: T;
        stepTitle?: T;
        stepDescription?: T;
        id?: T;
      };
  comparisonTable?: T;
  relatedPortfolioProjects?: T;
  relatedServices?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        tech?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        ogImage?: T;
      };
  viewCount?: T;
  status?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-types_select".
 */
export interface ServiceTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  icon?: T;
  cover?: T;
  color?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  client?: T;
  service?: T;
  type?: T;
  projectUrl?: T;
  projectDate?: T;
  content?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
        ogImage?: T;
      };
  viewCount?: T;
  status?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  date?: T;
  cover?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
      };
  readTime?: T;
  status?: T;
  featured?: T;
  viewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  color?: T;
  cover?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  author?: T;
  post?: T;
  content?: T;
  status?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  message?: T;
  type?: T;
  calculatorData?:
    | T
    | {
        projectType?: T;
        platform?: T;
        pagesCount?: T;
        additionalServices?: T;
        urgency?: T;
        estimatedPrice?: T;
        estimatedTimeline?: T;
      };
  source?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
      };
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-config".
 */
export interface CalculatorConfig {
  id: number;
  projectTypes?:
    | {
        /**
         * Наприклад: "Landing Page"
         */
        name: string;
        /**
         * Унікальний ідентифікатор: "landing"
         */
        slug: string;
        description?: string | null;
        /**
         * Назва іконки з Lucide: "layout", "store", "globe"
         */
        icon?: string | null;
        hasWebliumOption?: boolean | null;
        webliumBasePrice?: number | null;
        customBasePrice: number;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  pagesConfig: {
    webliumPricePerPage: number;
    customPricePerPage: number;
    minPages: number;
    maxPages: number;
    defaultPages: number;
  };
  additionalServices?:
    | {
        name: string;
        slug: string;
        description?: string | null;
        price: number;
        icon?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  urgencyOptions?:
    | {
        name: string;
        slug: string;
        description?: string | null;
        /**
         * 1.0 = стандарт, 1.5 = терміново (+50%), 0.9 = не поспішаємо (-10%)
         */
        coefficient: number;
        /**
         * Наприклад: "до 2 тижнів", "2-4 тижні"
         */
        timelineText?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  generalSettings: {
    currency: 'UAH' | 'USD' | 'EUR';
    showPriceFrom?: boolean | null;
    minimumOrderPrice?: number | null;
  };
  seo: {
    metaTitle: string;
    metaDescription: string;
    metaKeywords?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calculator-config_select".
 */
export interface CalculatorConfigSelect<T extends boolean = true> {
  projectTypes?:
    | T
    | {
        name?: T;
        slug?: T;
        description?: T;
        icon?: T;
        hasWebliumOption?: T;
        webliumBasePrice?: T;
        customBasePrice?: T;
        order?: T;
        id?: T;
      };
  pagesConfig?:
    | T
    | {
        webliumPricePerPage?: T;
        customPricePerPage?: T;
        minPages?: T;
        maxPages?: T;
        defaultPages?: T;
      };
  additionalServices?:
    | T
    | {
        name?: T;
        slug?: T;
        description?: T;
        price?: T;
        icon?: T;
        order?: T;
        id?: T;
      };
  urgencyOptions?:
    | T
    | {
        name?: T;
        slug?: T;
        description?: T;
        coefficient?: T;
        timelineText?: T;
        order?: T;
        id?: T;
      };
  generalSettings?:
    | T
    | {
        currency?: T;
        showPriceFrom?: T;
        minimumOrderPrice?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaKeywords?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}